env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react-hooks/recommended
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - functional
rules:
  import/extensions: 0
  import/no-unresolved: 0
  react/prop-types: 0
  no-console: 0
  functional/no-conditional-statement: 0
  functional/no-expression-statement: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statement: 0
  functional/no-throw-statement: 0
  testing-library/no-debug: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  react/function-component-definition:
    [2, { "namedComponents": "arrow-function" }]
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
